<?php

use Illuminate\Database\Seeder;

use App\Models\Manufacturer;

class ManufacturersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $manufacturers = [
            ['id' => 2001, 'name' => '1stPlayer'],
            ['id' => 2002, 'name' => 'A4-Tech'],
            ['id' => 2003, 'name' => 'Acbel'],
            ['id' => 2004, 'name' => 'Acer'],
            ['id' => 2005, 'name' => 'ADATA'],
            ['id' => 2006, 'name' => 'Aerocool'],
            ['id' => 2007, 'name' => 'Andyson'],
            ['id' => 2008, 'name' => 'Antec'],
            ['id' => 2009, 'name' => 'AOC'],
            ['id' => 2010, 'name' => 'Apple'],
            ['id' => 2011, 'name' => 'ARES'],
            ['id' => 2012, 'name' => 'Hacker Assassin'],
            ['id' => 2013, 'name' => 'Asus'],
            ['id' => 2014, 'name' => 'AXPRO'],
            ['id' => 2015, 'name' => 'Bencom'],
            ['id' => 2016, 'name' => 'BenQ'],
            ['id' => 2017, 'name' => 'Bosston'],
            ['id' => 2018, 'name' => 'Brother'],
            ['id' => 2019, 'name' => 'Canon'],
            ['id' => 2020, 'name' => 'CarePro'],
            ['id' => 2021, 'name' => 'Cisco'],
            ['id' => 2022, 'name' => 'Cooler Master'],
            ['id' => 2023, 'name' => 'CoolerPlus'],
            ['id' => 2024, 'name' => 'Corepad'],
            ['id' => 2025, 'name' => 'Corsair'],
            ['id' => 2026, 'name' => 'Cougar'],
            ['id' => 2027, 'name' => 'Crucial'],
            ['id' => 2028, 'name' => 'CyberPower'],
            ['id' => 2029, 'name' => 'D-Link'],
            ['id' => 2030, 'name' => 'Dahua'],
            ['id' => 2031, 'name' => 'DAIKIO'],
            ['id' => 2032, 'name' => 'DATO'],
            ['id' => 2033, 'name' => 'DeepCool'],
            ['id' => 2034, 'name' => 'Dell'],
            ['id' => 2035, 'name' => 'Delux'],
            ['id' => 2036, 'name' => 'Dintek'],
            ['id' => 2037, 'name' => 'Dragon'],
            ['id' => 2038, 'name' => 'DrayTek'],
            ['id' => 2039, 'name' => 'Ducky'],
            ['id' => 2040, 'name' => 'DXRacer'],
            ['id' => 2041, 'name' => 'E-Blue'],
            ['id' => 2042, 'name' => 'EATON'],
            ['id' => 2043, 'name' => 'Ensoho'],
            ['id' => 2044, 'name' => 'FSP'],
            ['id' => 2045, 'name' => 'Fuhlen'],
            ['id' => 2046, 'name' => 'GALAX'],
            ['id' => 2047, 'name' => 'Gamdias'],
            ['id' => 2048, 'name' => 'GEIL'],
            ['id' => 2049, 'name' => 'Genius'],
            ['id' => 2050, 'name' => 'GIGABYTE'],
            ['id' => 2051, 'name' => 'Glatten'],
            ['id' => 2052, 'name' => 'Golden Field'],
            ['id' => 2053, 'name' => 'Golden Link'],
            ['id' => 2054, 'name' => 'Gskill'],
            ['id' => 2055, 'name' => 'Haier'],
            ['id' => 2056, 'name' => 'Harman Kardon'],
            ['id' => 2057, 'name' => 'HP'],
            ['id' => 2058, 'name' => 'Huawei'],
            ['id' => 2059, 'name' => 'Huntkey'],
            ['id' => 2060, 'name' => 'Infosec'],
            ['id' => 2061, 'name' => 'Inno3D'],
            ['id' => 2062, 'name' => 'Intel'],
            ['id' => 2063, 'name' => 'Intex'],
            ['id' => 2064, 'name' => 'iRock'],
            ['id' => 2065, 'name' => 'iThink'],
            ['id' => 2066, 'name' => 'JBL'],
            ['id' => 2067, 'name' => 'Jetek'],
            ['id' => 2068, 'name' => 'KeySmart'],
            ['id' => 2069, 'name' => 'Khác'],
            ['id' => 2070, 'name' => 'Kingmax'],
            ['id' => 2071, 'name' => 'Kingston'],
            ['id' => 2072, 'name' => 'Konig'],
            ['id' => 2073, 'name' => 'LB-Link'],
            ['id' => 2074, 'name' => 'Lenovo'],
            ['id' => 2075, 'name' => 'Lexar'],
            ['id' => 2076, 'name' => 'LG'],
            ['id' => 2077, 'name' => 'Lightning'],
            ['id' => 2078, 'name' => 'LiteON'],
            ['id' => 2079, 'name' => 'Logitech'],
            ['id' => 2080, 'name' => 'Maruson'],
            ['id' => 2081, 'name' => 'MASSTEL'],
            ['id' => 2082, 'name' => 'Mercusys'],
            ['id' => 2083, 'name' => 'Microtech'],
            ['id' => 2084, 'name' => 'Mitsumi'],
            ['id' => 2085, 'name' => 'Motorola'],
            ['id' => 2086, 'name' => 'Motospeed'],
            ['id' => 2087, 'name' => 'MSI'],
            ['id' => 2088, 'name' => 'Netis'],
            ['id' => 2089, 'name' => 'Newmen'],
            ['id' => 2090, 'name' => 'Nimbus'],
            ['id' => 2091, 'name' => 'Nisoka'],
            ['id' => 2092, 'name' => 'Omega'],
            ['id' => 2093, 'name' => 'Oppo'],
            ['id' => 2094, 'name' => 'Orient'],
            ['id' => 2095, 'name' => 'Panram'],
            ['id' => 2096, 'name' => 'Patriot'],
            ['id' => 2097, 'name' => 'Philips'],
            ['id' => 2098, 'name' => 'Pisen'],
            ['id' => 2099, 'name' => 'Plextor'],
            ['id' => 2100, 'name' => 'PNY'],
            ['id' => 2101, 'name' => 'Qinlian'],
            ['id' => 2102, 'name' => 'Raidmax'],
            ['id' => 2103, 'name' => 'Rapoo'],
            ['id' => 2104, 'name' => 'Razer'],
            ['id' => 2105, 'name' => 'Remax'],
            ['id' => 2106, 'name' => 'Sama'],
            ['id' => 2107, 'name' => 'Samsung'],
            ['id' => 2108, 'name' => 'Santak'],
            ['id' => 2109, 'name' => 'Sarepo'],
            ['id' => 2110, 'name' => 'Seagate'],
            ['id' => 2111, 'name' => 'SeaSonic'],
            ['id' => 2112, 'name' => 'Segotep'],
            ['id' => 2113, 'name' => 'Sony'],
            ['id' => 2114, 'name' => 'Soundmax'],
            ['id' => 2115, 'name' => 'START'],
            ['id' => 2116, 'name' => 'SteelSeries'],
            ['id' => 2117, 'name' => 'TAKO'],
            ['id' => 2118, 'name' => 'Tân Hiệp Phát'],
            ['id' => 2119, 'name' => 'TEAM'],
            ['id' => 2120, 'name' => 'Tekshop'],
            ['id' => 2121, 'name' => 'Tenda'],
            ['id' => 2122, 'name' => 'Thermaltake'],
            ['id' => 2123, 'name' => 'Tigo'],
            ['id' => 2124, 'name' => 'Toshiba'],
            ['id' => 2125, 'name' => 'TP-Link'],
            ['id' => 2126, 'name' => 'Transcend'],
            ['id' => 2127, 'name' => 'V-Color'],
            ['id' => 2128, 'name' => 'ViewPaker'],
            ['id' => 2129, 'name' => 'Viewsonic'],
            ['id' => 2130, 'name' => 'Vision'],
            ['id' => 2131, 'name' => 'VNPT'],
            ['id' => 2132, 'name' => 'Volktek'],
            ['id' => 2133, 'name' => 'Vultech'],
            ['id' => 2134, 'name' => 'Western Digital'],
            ['id' => 2135, 'name' => 'Wincom'],
            ['id' => 2136, 'name' => 'Xigmatek'],
            ['id' => 2137, 'name' => 'Zidli'],
            ['id' => 2138, 'name' => 'ZOTAC'],
            ['id' => 2139, 'name' => 'Mionix'],
            ['id' => 2140, 'name' => 'Test'],
            ['id' => 2141, 'name' => 'Roccat'],
            ['id' => 2142, 'name' => 'Smart'],
            ['id' => 2143, 'name' => 'AMP'],
            ['id' => 2144, 'name' => 'Mega'],
            ['id' => 2145, 'name' => 'Wiko'],
            ['id' => 2146, 'name' => 'Kiwibox'],
            ['id' => 2147, 'name' => 'Eroxi'],
            ['id' => 2148, 'name' => 'Avexir'],
            ['id' => 2149, 'name' => 'Das Keyboard'],
            ['id' => 2150, 'name' => 'Phanteks'],
            ['id' => 2151, 'name' => 'Mad Catz'],
            ['id' => 2152, 'name' => 'Asrock'],
            ['id' => 2153, 'name' => 'Sandisk'],
            ['id' => 2154, 'name' => 'Tomotop'],
            ['id' => 2155, 'name' => 'Taurus'],
            ['id' => 2156, 'name' => 'NZXT'],
            ['id' => 2157, 'name' => 'ATX'],
            ['id' => 2158, 'name' => 'Comsory'],
            ['id' => 2159, 'name' => 'Colorful'],
            ['id' => 2160, 'name' => 'Ozone Gaming'],
            ['id' => 2161, 'name' => 'Audio Technica'],
            ['id' => 2162, 'name' => 'Beats'],
            ['id' => 2163, 'name' => 'AKG'],
            ['id' => 2164, 'name' => 'ADAALEN'],
            ['id' => 2165, 'name' => 'IPC'],
            ['id' => 2166, 'name' => 'Xiaomi'],
            ['id' => 2167, 'name' => 'OCZ'],
            ['id' => 2168, 'name' => 'Phinocom'],
            ['id' => 2169, 'name' => 'Linkpro'],
            ['id' => 2170, 'name' => 'Vivo'],
            ['id' => 2171, 'name' => 'Diio'],
            ['id' => 2172, 'name' => 'Sumtax'],
            ['id' => 2173, 'name' => 'Crossline'],
            ['id' => 2174, 'name' => 'Goldencom'],
            ['id' => 2175, 'name' => 'Tora'],
            ['id' => 2176, 'name' => 'Protos'],
        ];

        foreach ($manufacturers as $manufacturer) {
            Manufacturer::forceCreate([
                'id' => $manufacturer['id'],
                'code' => $this->generateCode($manufacturer['name']),
                'name' => $manufacturer['name'],
                'status' => true,
            ]);
        }
    }

    protected function generateCode($name)
    {
        $name = strtoupper(str_replace('-', '', $name));

        if (($pos = strpos($name, ' ')) === false) {
            return substr(preg_replace('/[^A-Za-z0-9]/', '', $name), 0, 6);
        }

        return preg_replace('/[^A-Za-z0-9]/', '', substr($name, 0, 1).substr($name, $pos + 1, 5));
    }
}
